openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: My API description

servers:
 - url: /api

components:
  schemas:
    Person:
      type: object
      required:
        - lname
      properties:
        lname:
          type: string
        fname:
          type: string
        history:
          type: dict
  parameters:
    lname:
      name: lname
      in: path
      required: true
      schema:
        type: string

paths:
  /people:
    get:
      summary: Get lisf of all people
      tags:
        - People
      operationId: people.get_all_people
      responses:
        '200':
          description: Successfully read all people
    post:
      summary: Create a new person
      tags:
        - People
      operationId: people.create_person
      requestBody:
        description: Person to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '201':
          description: Successfully created a new person

  /people/{lname}:
    get:
      summary: Get a person by last name
      tags:
        - People
      operationId: people.get_person
      description: Get a person by last name
      parameters:
        - $ref: '#/components/parameters/lname'
      responses:
        '200':
          description: Successfully read a person
    put:
      summary: Update a person by last name
      tags:
        - People
      operationId: people.update_person
      parameters:
        - $ref: '#/components/parameters/lname'
      requestBody:
        description: Person to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '200':
          description: Successfully updated a person
    delete:
      summary: Delete a person by last name
      tags:
        - People
      operationId: people.delete_person
      parameters:
        - $ref: '#/components/parameters/lname'
      responses:
        '204':
          description: Successfully deleted a person
  /trips/lname:
    get:
      summary: Get all
