openapi: 3.0.0
info:
  title: "BIGGS_TAXI"
  description: "An API about BIGGS taxi app."
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Order:
      type: object
      properties:
        customer_id:
          type: integer
        pickup_location:
          type: string
        destination:
          type: string
        distance:
          type: number
        car_category:
          type: string
        start_time:
          type: string
        end_time:
          type: string
        total_ride_time:
          type: integer
        order_amount:
          type: integer
      required:
        - customer_id
        - pickup_location
        - destination
        - car_category
        - order_amount
        - start_time
        - end_time
        - total_ride_time


paths:

  /orders:
    get:
      operationId: "orders.get_all"
      tags:
        - "Orders"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"
    post:
      operationId: "orders.create_order"
      tags:
        - "Orders"
      summary: "Getting order information"
      requestBody:
        description: "Order to create"
        required: True
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "201":
          description: "The order data has been successfully received"

  /orders/{id}:
    get:
      operationId: "orders.get_all_person"
      tags:
        - "Orders"
      summary: "get all the trips of a certain user"
      responses:
        "200":
          description: "trips have been successfully received"







