openapi: 3.0.0
info:
  title: "BIGGS_TAXI"
  description: "An API about BIGGS taxi app."
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    CreateUser: 
      type: "object"
      required:
        - fullname
        - username
        - email
        - password
      properties:
        fullname:
          type: "string"
        username:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"
    EnterUser:
      type: "object"
      required:
        - login_or_email
        - password
      properties:
        login_or_email:
          type: "string"
        password:
          type: "string"


paths:
  /:
    get:
      operationId: "main.index"
      tags:
        - "Start window"
      summary: "Opens the start window."
      responses:
        "200":
          description: "Start window was opened successfully."

  /registration:
    post:
      operationId: "registration_and_entrance.registration"
      tags:
        - "Register"
      summary: "Register a new user."
      requestBody:
          description: "User to register"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "user"
                $ref: "#/components/schemas/CreateUser"
      responses:
        "201":
          description: "User was successfully registered."
        "400":
          description: "Mistake in username or email."

  /entrance:
    post:
      operationId: "registration_and_entrance.entrance"
      tags:
        - "Enter"
      summary: "User enters with their email and password."
      requestBody:
          description: "User enters"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "user"
                $ref: "#/components/schemas/EnterUser"
      responses:
        "200":
          description: "User successfully entered."
        "400":
          description: "Wrong password."